"use client";

import { Card } from "@/components/ui/card";
import { PageHeader, StatTile } from "@/components/page-header";
import { parentWeekly, humanDue } from "@/lib/mock-data";
import { Shield, Info } from "lucide-react";

const DAYS = ["M", "T", "W", "T", "F", "S", "S"];

export default function ParentPage() {
  const totalStudy = parentWeekly.studyHours.reduce((s, x) => s + x, 0);
  const totalFocus = parentWeekly.focusHours.reduce((s, x) => s + x, 0);
  const avgWellness = Math.round(
    parentWeekly.wellness.reduce((s, x) => s + x, 0) / parentWeekly.wellness.length
  );

  return (
    <div>
      <PageHeader
        eyebrow="System"
        title="Parent view."
        subtitle="A demo dashboard that shows what a guardian would see if this student opted in."
        actions={
          <span className="inline-flex items-center gap-1.5 rounded-full border border-amber-400/30 bg-amber-400/10 px-2.5 py-1 text-xs text-amber-200">
            <Info className="h-3.5 w-3.5" /> demo · mock data
          </span>
        }
      />

      <Card className="mb-6 flex items-start gap-3 border-cyan-400/20 bg-cyan-400/5 p-4 text-sm">
        <Shield className="mt-0.5 h-4 w-4 shrink-0 text-cyan-300" />
        <div className="text-cyan-100/90">
          The student toggles this view on in{" "}
          <span className="text-cyan-200 underline underline-offset-2">
            Settings → Parent monitoring
          </span>
          . Without their consent, this page is empty. Nothing here is shared
          without permission.
        </div>
      </Card>

      <div className="mb-6 grid gap-4 md:grid-cols-4">
        <StatTile
          label="Study this week"
          value={`${totalStudy.toFixed(1)}h`}
          hint="24.8h target"
          accent="cyan"
        />
        <StatTile
          label="Focus this week"
          value={`${totalFocus.toFixed(1)}h`}
          hint={`${((totalFocus / totalStudy) * 100).toFixed(0)}% of study time`}
          accent="emerald"
        />
        <StatTile
          label="Assignments done"
          value={`${parentWeekly.assignmentsDone}/${parentWeekly.assignmentsTotal}`}
          hint="3 remaining this week"
          accent="violet"
        />
        <StatTile
          label="Avg wellness"
          value={avgWellness}
          hint="calmer than last week"
          accent="rose"
        />
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <ChartCard
          title="Study & focus hours"
          hint="daily this week"
          data={[
            { label: "study", color: "#67e8f9", values: parentWeekly.studyHours },
            { label: "focus", color: "#86efac", values: parentWeekly.focusHours },
          ]}
          maxY={6}
        />
        <ChartCard
          title="Wellness trend"
          hint="0–100"
          data={[
            { label: "wellness", color: "#a78bfa", values: parentWeekly.wellness },
          ]}
          maxY={100}
        />
        <ChartCard
          title="Screen time during study"
          hint="minutes on task"
          data={[
            {
              label: "on-task minutes",
              color: "#fda4af",
              values: parentWeekly.screenTimeStudy,
            },
          ]}
          maxY={120}
        />

        <Card className="bg-neutral-950/60 p-6">
          <h3 className="mb-4 text-sm font-medium text-neutral-100">
            Upcoming deadlines
          </h3>
          <ul className="space-y-2">
            {parentWeekly.upcomingDeadlines.map((d) => (
              <li
                key={d.title}
                className="flex items-center justify-between rounded-lg border border-neutral-900 bg-black/40 px-3 py-2 text-sm"
              >
                <span className="text-neutral-100">{d.title}</span>
                <span className="text-xs text-neutral-500">{humanDue(d.when)}</span>
              </li>
            ))}
          </ul>
        </Card>
      </div>

      <Card className="mt-6 bg-neutral-950/60 p-6">
        <div className="mb-2 flex items-center gap-2">
          <span className="rounded bg-cyan-400/10 px-2 py-0.5 text-[10px] uppercase tracking-[0.16em] text-cyan-300">
            weekly summary
          </span>
          <span className="text-[11px] text-neutral-500">generated by Anchor</span>
        </div>
        <p className="text-sm leading-relaxed text-neutral-200">
          {parentWeekly.summary}
        </p>
      </Card>
    </div>
  );
}

function ChartCard({
  title,
  hint,
  data,
  maxY,
}: {
  title: string;
  hint: string;
  data: { label: string; color: string; values: number[] }[];
  maxY: number;
}) {
  const w = 480;
  const h = 160;
  const padL = 24;
  const padB = 20;
  return (
    <Card className="bg-neutral-950/60 p-6">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-sm font-medium text-neutral-100">{title}</h3>
        <span className="text-xs text-neutral-500">{hint}</span>
      </div>
      <svg viewBox={`0 0 ${w} ${h}`} className="w-full">
        {/* grid */}
        {[0, 0.25, 0.5, 0.75, 1].map((f, i) => (
          <line
            key={i}
            x1={padL}
            x2={w}
            y1={h - padB - (h - padB - 10) * f}
            y2={h - padB - (h - padB - 10) * f}
            stroke="rgba(255,255,255,0.05)"
          />
        ))}
        {DAYS.map((d, i) => (
          <text
            key={i}
            x={padL + ((w - padL) / (DAYS.length - 1)) * i}
            y={h - 4}
            textAnchor="middle"
            fontSize="10"
            fill="#525252"
          >
            {d}
          </text>
        ))}
        {data.map((series, si) => {
          const points = series.values
            .map((v, i) => {
              const x = padL + ((w - padL) / (series.values.length - 1)) * i;
              const y =
                h - padB - ((v / maxY) * (h - padB - 10));
              return `${x},${y}`;
            })
            .join(" ");
          return (
            <g key={si}>
              <polyline
                fill="none"
                stroke={series.color}
                strokeWidth="2"
                points={points}
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              {series.values.map((v, i) => {
                const x = padL + ((w - padL) / (series.values.length - 1)) * i;
                const y = h - padB - ((v / maxY) * (h - padB - 10));
                return <circle key={i} cx={x} cy={y} r="2.5" fill={series.color} />;
              })}
            </g>
          );
        })}
      </svg>
      <div className="mt-2 flex gap-3">
        {data.map((series) => (
          <span
            key={series.label}
            className="inline-flex items-center gap-1.5 text-xs text-neutral-400"
          >
            <span
              className="h-2 w-2 rounded-full"
              style={{ background: series.color }}
            />
            {series.label}
          </span>
        ))}
      </div>
    </Card>
  );
}
